version: 2
jobs:
  trusty:
    docker:
      - image: ubuntu:trusty
    steps:
      - checkout
      - run: cat /etc/os-release
  xenial:
    docker:
      - image: ubuntu:xenial
    steps:
      - checkout
      - run: cat /etc/os-release
  bionic:
    docker:
      - image: ubuntu:bionic
    steps:
      - checkout
      - run: cat /etc/os-release
workflows:
  version: 2
  build:
    jobs:
      - trusty
      - xenial
      - bionic