version: 2

install-jq: &install-jq
  name: Install jq
  command: |
    wget -O /usr/local/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
    chmod +x /usr/local/bin/jq

test-ubuntu: &test-ubuntu
  steps:
    - checkout
    - run: cat /etc/*-release
    - run: apt-get update -qq && apt-get install -y wget
    - run:
        <<: *install-jq
    - run: DIST=ubuntu ./test/test-packages.sh

test-debian: &test-debian
  steps:
    - checkout
    - run: cat /etc/*-release
    - run: apt-get update -qq && apt-get install -y wget
    - run:
        <<: *install-jq
    - run: DIST=debian ./test/test-packages.sh

test-centos: &test-centos
  steps:
    - checkout
    - run: cat /etc/*-release
    - run: yum update -y -q && yum install -y epel-release wget
    - run:
        <<: *install-jq
    - run: DIST=centos ./test/test-packages.sh

test-opensuse: &test-opensuse
  steps:
    - checkout
    - run: cat /etc/*-release
    - run: zypper --quiet update && zypper install -y wget
    - run:
        <<: *install-jq
    - run: DIST=opensuse ./test/test-packages.sh

jobs:
  trusty:
    <<: *test-ubuntu
    docker:
      - image: ubuntu:trusty
  xenial:
    <<: *test-ubuntu
    docker:
      - image: ubuntu:xenial
  bionic:
    <<: *test-ubuntu
    docker:
      - image: ubuntu:bionic
  jessie:
    <<: *test-debian
    docker:
      - image: debian:jessie
  stretch:
    <<: *test-debian
    docker:
      - image: debian:stretch
  centos6:
    <<: *test-centos
    docker:
      - image: centos:6
  centos7:
    <<: *test-centos
    docker:
      - image: centos:7
  opensuse42:
    <<: *test-opensuse
    docker:
      - image: opensuse/leap:42
workflows:
  version: 2
  build:
    jobs:
      - trusty
      - xenial
      - bionic
      - jessie
      - stretch
      - centos6
      - centos7
      - opensuse42