version: 2

defaults: &defaults
  steps:
    - checkout
    - run: cat /etc/*-release

jobs:
  trusty:
    <<: *defaults
    docker:
      - image: ubuntu:trusty
  xenial:
    <<: *defaults
    docker:
      - image: ubuntu:xenial
  bionic:
    <<: *defaults
    docker:
      - image: ubuntu:bionic
  jessie:
    <<: *defaults
    docker:
      - image: debian:jessie
  stretch:
    <<: *defaults
    docker:
      - image: debian:stretch
  centos6:
    <<: *defaults
    docker:
      - image: centos:6
  centos7:
    <<: *defaults
    docker:
      - image: centos:7
workflows:
  version: 2
  build:
    jobs:
      - trusty
      - xenial
      - bionic
      - jessie
      - stretch
      - centos6
      - centos7